github.com:
    users:
        Majestic9169:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: Majestic9169
